package PROJECT;

import com.sun.glass.events.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user1
 */
public class MyAddStaff extends javax.swing.JInternalFrame {

    private PreparedStatement pstmt;
    private ResultSet rs;
    private DefaultTableModel model = new DefaultTableModel();
    static int SUPPLIER_ID;

    public MyAddStaff() {

        initComponents();
//        snameTextField.requestFocusInWindow();        
        addRecordIntoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        reportButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        fnameTextField = new javax.swing.JTextField();
        mobnoTextField = new javax.swing.JTextField();
        joinDateChooser = new com.toedter.calendar.JDateChooser();
        resignDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        addTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        joindtTextField = new javax.swing.JTextField();
        resigndtTextField = new javax.swing.JTextField();

        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1385, 700));

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STAFF DETAIL ENTRY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1079, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel7.setText("Search:");

        searchTextField.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        searchTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "FATHER'S NAME", "MOB NO", "JOIN DATE", "RESIGN DATE", "ADDRESS"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        reportButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reportButton.setText("REPORT OF STAFF ");
        reportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(reportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("Full Name");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("Father's Name");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setText("ID");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setText("Mobile No.");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setText("Address");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel18.setText("Joining Date");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel19.setText("Resiging Date");

        idTextField.setEditable(false);
        idTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        nameTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyTyped(evt);
            }
        });

        fnameTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        fnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameTextFieldKeyTyped(evt);
            }
        });

        mobnoTextField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        mobnoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobnoTextFieldKeyTyped(evt);
            }
        });

        joinDateChooser.setAutoscrolls(true);
        joinDateChooser.setDateFormatString("d MMM, yyyy");

        resignDateChooser.setAutoscrolls(true);
        resignDateChooser.setDateFormatString("d MMM, yyyy");

        addTextArea.setColumns(20);
        addTextArea.setLineWrap(true);
        addTextArea.setRows(5);
        jScrollPane1.setViewportView(addTextArea);

        saveButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        saveButton.setText("ENTRY");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        joindtTextField.setEditable(false);

        resigndtTextField.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addComponent(deleteButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(resigndtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resignDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(mobnoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(joindtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(joinDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(joindtTextField)
                                .addGap(1, 1, 1))
                            .addComponent(joinDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(resigndtTextField))
                        .addComponent(resignDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(7, 7, 7)))
                .addGap(7, 7, 7)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ******************************************************************************************
     */
    public void addRecordIntoTable() {
        pstmt = null;
        rs = null;
        try {
            String s_name = searchTextField.getText().trim().toUpperCase();
            if (s_name.equalsIgnoreCase("")) {
                pstmt = MyLogin.con.prepareStatement("select * from STAFF_DETAIL", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            } else {
                pstmt = MyLogin.con.prepareStatement("select * from STAFF_DETAIL where S_NAME like '" + s_name + "%'", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            }
            rs = pstmt.executeQuery();
            pstmt.clearParameters();

            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            while (tm.getRowCount() > 0) {
                tm.removeRow(0);
            }
            while (rs.next()) {
                Object kk[] = {rs.getInt("S_ID"), rs.getString("S_NAME"), rs.getString("S_F_NAME"), rs.getString("S_MOB_NO"), rs.getString("S_JOIN_DT"), rs.getString("S_REGN_DT"), rs.getString("S_ADDRESS")};
                tm.addRow(kk);
            }
        } catch (Exception e) {
            System.out.println(" Error inside addrecordinto table " + e);
        }
    }

    /**
     * ***************************************************************************************************
     */
    private void clearFields() {
        idTextField.setText("");
        nameTextField.setText("");
        fnameTextField.setText("");
        mobnoTextField.setText("");
        joinDateChooser.setDate(null);
        resignDateChooser.setDate(null);
        joindtTextField.setText("");
        resigndtTextField.setText("");
        addTextArea.setText("");
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        String sname, fname, mobno, join_dt, resign_dt, address;
        sname = nameTextField.getText().trim().toUpperCase();
        fname = fnameTextField.getText().trim().toUpperCase();
        mobno = mobnoTextField.getText().trim();
        address = addTextArea.getText().trim().toUpperCase();
        DateFormat df;
        df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
        if (sname.equalsIgnoreCase("") || fname.equalsIgnoreCase("") || mobno.equals("") || address.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "FILL ALL DETAILS CAREFULLY (Except Id)", "SAVE RECORD", JOptionPane.ERROR_MESSAGE);
        } else if (mobno.length() != 10) {
            JOptionPane.showMessageDialog(null, "MOBILE  NO CANNOT BE LESS THAN 10 DIGITS)", "SAVE RECORD", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                resign_dt = df.format(resignDateChooser.getDate());
            } catch (Exception e) {
                System.out.println("" + e);
                resign_dt = "-";
            }
            try {
                join_dt = df.format(joinDateChooser.getDate());

                pstmt = MyLogin.con.prepareStatement("insert into STAFF_DETAIL (S_NAME,S_F_NAME,S_MOB_NO,S_JOIN_DT,S_REGN_DT,S_ADDRESS) values(?,?,?,?,?,?)", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                pstmt.setString(1, sname);
                pstmt.setString(2, fname);
                pstmt.setString(3, mobno);
                pstmt.setString(4, join_dt);
                pstmt.setString(5, resign_dt);
                pstmt.setString(6, address);
                int i = pstmt.executeUpdate();
                pstmt.clearParameters();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Entry successfull", "Staff Entry", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                    addRecordIntoTable();
                } else {
                    System.out.println("Problem in insertion data in DEALER_DETAIL TABLE");
                }
            } catch (Exception e) {
                System.out.println("Error " + e);
                JOptionPane.showMessageDialog(null, "FILL ALL DETAILS CAREFULLY (Except Id)", "SAVE RECORD", JOptionPane.ERROR_MESSAGE);
            }
        }
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * ***********************************************************************
     */
    public void test() {
        pstmt = null;
        rs = null;
        try {
            int s_id = Integer.parseInt(idTextField.getText());
            pstmt = MyLogin.con.prepareStatement("select * from STAFF_DETAIL where S_ID = ?", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            pstmt.setInt(1, s_id);
            rs = pstmt.executeQuery();
            pstmt.clearParameters();
            rs.next();
        } catch (Exception e) {
            System.out.println(" Error in test " + e);
        }
    }
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:     
        String s_name, fname, mobno, address, joindt = "", resigndt = "-";
        s_name = nameTextField.getText().trim().toUpperCase();
        fname = fnameTextField.getText().trim().toUpperCase();
        mobno = mobnoTextField.getText().trim();
        address = addTextArea.getText().trim().toUpperCase();
        DateFormat df;
        df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
        try {
            joindt = df.format(joinDateChooser.getDate());
        } catch (Exception e) {
            joindt = joindtTextField.getText().trim();
        }
        try {
            resigndt = df.format(resignDateChooser.getDate());
        } catch (Exception e) {
            resigndt = resigndtTextField.getText().trim();
        }
        try {
            int id = Integer.parseInt(idTextField.getText().trim());
            if (!(s_name.equalsIgnoreCase("") || fname.equalsIgnoreCase("") || mobno.equalsIgnoreCase("") || address.equalsIgnoreCase(""))) {
                if (mobno.length() != 10) {
                    JOptionPane.showMessageDialog(null, "CONTACT NO CANNOT BE LESS THAN 10 DIGITS)", "UPDATION  ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    test();
                    if (!(s_name.equalsIgnoreCase(rs.getString("S_NAME")) && fname.equalsIgnoreCase(rs.getString("S_F_NAME")) && mobno.equalsIgnoreCase(rs.getString("S_MOB_NO")) && address.equalsIgnoreCase(rs.getString("S_ADDRESS")) && joindt.equalsIgnoreCase(rs.getString("S_JOIN_DT")) && resigndt.equalsIgnoreCase(rs.getString("S_REGN_DT")))) {
                        pstmt = MyLogin.con.prepareStatement("update STAFF_DETAIL set S_NAME = ?,S_F_NAME = ?,S_MOB_NO = ?,S_JOIN_DT = ?,S_REGN_DT = ?, S_ADDRESS = ? where S_ID = ?", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                        pstmt.setString(1, s_name);
                        pstmt.setString(2, fname);
                        pstmt.setString(3, mobno);
                        pstmt.setString(4, joindt);
                        pstmt.setString(5, resigndt);
                        pstmt.setString(6, address);
                        pstmt.setInt(7, id);
                        int i = pstmt.executeUpdate();
                        pstmt.clearParameters();
                        if (i > 0) {
                            JOptionPane.showMessageDialog(null, "Detail Updated Successfully", "UPDATE", JOptionPane.INFORMATION_MESSAGE);
                            clearFields();
                            addRecordIntoTable();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "NO CHANGES MADE", "UPDATION CANCLED", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "NO CHANGES MADE", "UPDATION CANCLED", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "CHOOSE ANY RECORD TO UPDATE", "ZERO SUPPLIER SELECTED", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println("Exception inside update button " + e);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:         
        clearFields();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void searchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyReleased

        addRecordIntoTable();
    }//GEN-LAST:event_searchTextFieldKeyReleased

    private void reportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportButtonActionPerformed
        // TODO add your handling code here:
        reportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try {
            GenerateReport ob = new GenerateReport();
            ob.showStaffReport();
        } catch (Exception e) {
            System.out.println("exception " + e);
        }
        reportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    }//GEN-LAST:event_reportButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:        
        try {
            int id = Integer.parseInt(idTextField.getText().trim());
            int j = JOptionPane.showConfirmDialog(null, "Are you sure you want to permanently delete this record", "Delete Record", JOptionPane.CANCEL_OPTION);
            if (j == 0) {
                pstmt = MyLogin.con.prepareStatement("delete from STAFF_DETAIL where S_ID = ?");
                pstmt.setInt(1, id);
                int i = pstmt.executeUpdate();
                pstmt.clearParameters();
                if (i == 1) {
                    JOptionPane.showMessageDialog(null, "One record deleted Successfully", "DELETE", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                    addRecordIntoTable();
                } else {
                    JOptionPane.showMessageDialog(null, "Deletion Failed", "DELETE", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Deletion canceled", "DELETE", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "SELECT ANY DETAIL FROM TABLE TO DELETE", "ZERO ROW SELECTED", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            System.out.println("Exception inside delete button " + e);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowIndex = jTable1.getSelectedRow();
            if (rowIndex > -1) {
                idTextField.setText(model.getValueAt(rowIndex, 0).toString());
                nameTextField.setText(model.getValueAt(rowIndex, 1).toString());
                fnameTextField.setText(model.getValueAt(rowIndex, 2).toString());
                mobnoTextField.setText(model.getValueAt(rowIndex, 3).toString());
                /*   joinDateChooser.setDate(Date.valueOf(model.getValueAt(rowIndex ,4).toString()));
                 if(model.getValueAt(rowIndex ,5).toString().equalsIgnoreCase("-")){
                     resignDateChooser.setDate(null);                
                 }else{
                     resignDateChooser.setDate(Date.valueOf(model.getValueAt(rowIndex ,5).toString()));                
                 }        */
                joindtTextField.setText(model.getValueAt(rowIndex, 4).toString());
                resigndtTextField.setText(model.getValueAt(rowIndex, 5).toString());
                addTextArea.setText(model.getValueAt(rowIndex, 6).toString());
            }
        } catch (Exception e) {
            System.out.println("Exception " + e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param evt
     *
     * @param
     * letters*************************************************************************************
     */
    public void checkLetters(java.awt.event.KeyEvent evt, String letters) {
        char cr = evt.getKeyChar();
        if (!((Character.isLetter(cr)) || (cr == KeyEvent.VK_BACKSPACE) || (cr == KeyEvent.VK_SPACE))) {
            getToolkit().beep();
            evt.consume();
        }
        if (letters.length() > 49) {
            getToolkit().beep();
            evt.consume();
        }
    }

    /**
     * @param evt
     * @param fieldname
     *
     *
     **************************************************************************************
     */
    public void checkNumbers(java.awt.event.KeyEvent evt, javax.swing.JTextField fieldname) {
        char cr = evt.getKeyChar();
        if (!(Character.isDigit(cr) || (cr == KeyEvent.VK_BACKSPACE) || cr == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        if (fieldname.getText().length() > 9) {
            getToolkit().beep();
            evt.consume();
        }
    }
    private void searchTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyTyped
        // TODO add your handling code here:
        checkLetters(evt, searchTextField.getText());
    }//GEN-LAST:event_searchTextFieldKeyTyped

    private void mobnoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobnoTextFieldKeyTyped
        checkNumbers(evt, mobnoTextField);
    }//GEN-LAST:event_mobnoTextFieldKeyTyped

    private void fnameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameTextFieldKeyTyped
        checkLetters(evt, fnameTextField.getText());
    }//GEN-LAST:event_fnameTextFieldKeyTyped

    private void nameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyTyped
        checkLetters(evt, nameTextField.getText());
    }//GEN-LAST:event_nameTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addTextArea;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser joinDateChooser;
    private javax.swing.JTextField joindtTextField;
    private javax.swing.JTextField mobnoTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton reportButton;
    private javax.swing.JButton resetButton;
    private com.toedter.calendar.JDateChooser resignDateChooser;
    private javax.swing.JTextField resigndtTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

}
